services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        FLUTTER_VERSION: "3.44.7"
        ANDROID_CMDLINE_TOOLS_VERSION: "15859902"

    volumes:
      - ..:/workspace:cached
      - jellyfinity-home:/home/vscode
      - ~/.ssh/agent.sock:/ssh-agent

    working_dir: /workspace

    command: sleep infinity

    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      ANDROID_SDK_ROOT: /opt/android-sdk
      ANDROID_HOME: /opt/android-sdk
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      PUB_CACHE: /home/vscode/.pub-cache
      ADB_SERVER_SOCKET: tcp:host.docker.internal:5037
      SSH_AUTH_SOCK: /ssh-agent

volumes:
  jellyfinity-home:
    name: jellyfinity-home
